<?php

/**
 * StatsAPIApi
 * PHP version 8.1
 *
 * @category Class
 * @package  IONOS\NextcloudPSS\AddonsAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

declare(strict_types=1);

/**
 * SPDX-FileCopyrightText: 2025 STRATO GmbH
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

/**
 * IONOS Nextcloud PSS Addons API
 *
 * PHP API client for the IONOS Nextcloud PSS Addons API
 *
 * The version of the OpenAPI document: 2.0.0-20260429080405
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IONOS\NextcloudPSS\AddonsAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use IONOS\NextcloudPSS\AddonsAPI\Client\ApiException;
use IONOS\NextcloudPSS\AddonsAPI\Client\Configuration;
use IONOS\NextcloudPSS\AddonsAPI\Client\FormDataProcessor;
use IONOS\NextcloudPSS\AddonsAPI\Client\HeaderSelector;
use IONOS\NextcloudPSS\AddonsAPI\Client\ObjectSerializer;

/**
 * StatsAPIApi Class Doc Comment
 *
 * @category Class
 * @package  IONOS\NextcloudPSS\AddonsAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StatsAPIApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'updateStats' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation updateStats
     *
     * Reports the current active user count from the Nextcloud instance to PSS
     *
     * @param  string $brand brand (required)
     * @param  string $extRef extRef (required)
     * @param  \IONOS\NextcloudPSS\AddonsAPI\Client\Model\StatsUpdateRequest $statsUpdateRequest statsUpdateRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateStats'] to see the possible values for this operation
     *
     * @throws \IONOS\NextcloudPSS\AddonsAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function updateStats($brand, $extRef, $statsUpdateRequest, string $contentType = self::contentTypes['updateStats'][0])
    {
        $this->updateStatsWithHttpInfo($brand, $extRef, $statsUpdateRequest, $contentType);
    }

    /**
     * Operation updateStatsWithHttpInfo
     *
     * Reports the current active user count from the Nextcloud instance to PSS
     *
     * @param  string $brand (required)
     * @param  string $extRef (required)
     * @param  \IONOS\NextcloudPSS\AddonsAPI\Client\Model\StatsUpdateRequest $statsUpdateRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateStats'] to see the possible values for this operation
     *
     * @throws \IONOS\NextcloudPSS\AddonsAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateStatsWithHttpInfo($brand, $extRef, $statsUpdateRequest, string $contentType = self::contentTypes['updateStats'][0])
    {
        $request = $this->updateStatsRequest($brand, $extRef, $statsUpdateRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IONOS\NextcloudPSS\AddonsAPI\Client\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IONOS\NextcloudPSS\AddonsAPI\Client\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\IONOS\NextcloudPSS\AddonsAPI\Client\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation updateStatsAsync
     *
     * Reports the current active user count from the Nextcloud instance to PSS
     *
     * @param  string $brand (required)
     * @param  string $extRef (required)
     * @param  \IONOS\NextcloudPSS\AddonsAPI\Client\Model\StatsUpdateRequest $statsUpdateRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateStats'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateStatsAsync($brand, $extRef, $statsUpdateRequest, string $contentType = self::contentTypes['updateStats'][0])
    {
        return $this->updateStatsAsyncWithHttpInfo($brand, $extRef, $statsUpdateRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateStatsAsyncWithHttpInfo
     *
     * Reports the current active user count from the Nextcloud instance to PSS
     *
     * @param  string $brand (required)
     * @param  string $extRef (required)
     * @param  \IONOS\NextcloudPSS\AddonsAPI\Client\Model\StatsUpdateRequest $statsUpdateRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateStats'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateStatsAsyncWithHttpInfo($brand, $extRef, $statsUpdateRequest, string $contentType = self::contentTypes['updateStats'][0])
    {
        $returnType = '';
        $request = $this->updateStatsRequest($brand, $extRef, $statsUpdateRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response ? $response->getStatusCode() : $exception->getCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response ? $response->getHeaders() : [],
                        $response ? (string) $response->getBody() : null
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateStats'
     *
     * @param  string $brand (required)
     * @param  string $extRef (required)
     * @param  \IONOS\NextcloudPSS\AddonsAPI\Client\Model\StatsUpdateRequest $statsUpdateRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateStats'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateStatsRequest($brand, $extRef, $statsUpdateRequest, string $contentType = self::contentTypes['updateStats'][0])
    {

        // verify the required parameter 'brand' is set
        if ($brand === null || (is_array($brand) && count($brand) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $brand when calling updateStats'
            );
        }

        // verify the required parameter 'extRef' is set
        if ($extRef === null || (is_array($extRef) && count($extRef) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $extRef when calling updateStats'
            );
        }

        // verify the required parameter 'statsUpdateRequest' is set
        if ($statsUpdateRequest === null || (is_array($statsUpdateRequest) && count($statsUpdateRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $statsUpdateRequest when calling updateStats'
            );
        }


        $resourcePath = '/addons/{brand}/{extRef}/stats';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($brand !== null) {
            $resourcePath = str_replace(
                '{' . 'brand' . '}',
                ObjectSerializer::toPathValue($brand),
                $resourcePath
            );
        }
        // path params
        if ($extRef !== null) {
            $resourcePath = str_replace(
                '{' . 'extRef' . '}',
                ObjectSerializer::toPathValue($extRef),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($statsUpdateRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($statsUpdateRequest));
            } else {
                $httpBody = $statsUpdateRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
