<?php

/**
 * StatsAPIApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  IONOS\NextcloudPSS\AddonsAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

declare(strict_types=1);

/**
 * SPDX-FileCopyrightText: 2025 STRATO GmbH
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

/**
 * IONOS Nextcloud PSS Addons API
 *
 * PHP API client for the IONOS Nextcloud PSS Addons API
 *
 * The version of the OpenAPI document: 2.0.0-20260429080405
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace IONOS\NextcloudPSS\AddonsAPI\Client\Test\Api;

use \IONOS\NextcloudPSS\AddonsAPI\Client\Configuration;
use \IONOS\NextcloudPSS\AddonsAPI\Client\ApiException;
use \IONOS\NextcloudPSS\AddonsAPI\Client\ObjectSerializer;
use \IONOS\NextcloudPSS\AddonsAPI\Client\Api\StatsAPIApi;
use \IONOS\NextcloudPSS\AddonsAPI\Client\Model\StatsUpdateRequest;
use GuzzleHttp\Client;
use GuzzleHttp\Handler\MockHandler;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Psr7\Response;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use PHPUnit\Framework\TestCase;

/**
 * StatsAPIApiTest Class Doc Comment
 *
 * @category Class
 * @package  IONOS\NextcloudPSS\AddonsAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StatsAPIApiTest extends TestCase
{
    /**
     * @var StatsAPIApi
     */
    protected $api;

    /**
     * @var MockHandler
     */
    protected $mockHandler;

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->mockHandler = new MockHandler();
        $handlerStack = HandlerStack::create($this->mockHandler);
        $client = new Client(['handler' => $handlerStack]);
        $config = Configuration::getDefaultConfiguration();
        $this->api = new StatsAPIApi($client, $config);
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for updateStats
     *
     * Reports the current active user count from the Nextcloud instance to PSS.
     *
     */
    public function testUpdateStats()
    {
        $responseBody = '';
        $this->mockHandler->append(new Response(204, [], $responseBody));

        $brand = 'test_brand';
        $extRef = 'test_extRef';

        $users = new \IONOS\NextcloudPSS\AddonsAPI\Client\Model\UserStats();
        $users->setExistingUsers(42);

        $statsUpdateRequest = new \IONOS\NextcloudPSS\AddonsAPI\Client\Model\StatsUpdateRequest();
        $statsUpdateRequest->setTimestamp(new \DateTime('2026-04-29T08:04:05Z'));
        $statsUpdateRequest->setUsers($users);

        $this->api->updateStats($brand, $extRef, $statsUpdateRequest);

        $lastRequest = $this->mockHandler->getLastRequest();
        $body = json_decode((string) $lastRequest->getBody(), true);
        $this->assertArrayHasKey('timestamp', $body);
        $this->assertEquals(42, $body['users']['existingUsers']);
    }

    /**
     * Test case for updateStats with HTTP info
     *
     * Reports the current active user count from the Nextcloud instance to PSS.
     *
     */
    public function testUpdateStatsWithHttpInfo()
    {
        $responseBody = '';
        $this->mockHandler->append(new Response(204, ['Content-Type' => 'application/json'], $responseBody));

        $brand = 'test_brand';
        $extRef = 'test_extRef';

        $users = new \IONOS\NextcloudPSS\AddonsAPI\Client\Model\UserStats();
        $users->setExistingUsers(5);

        $statsUpdateRequest = new \IONOS\NextcloudPSS\AddonsAPI\Client\Model\StatsUpdateRequest();
        $statsUpdateRequest->setTimestamp(new \DateTime('2026-04-29T08:04:05Z'));
        $statsUpdateRequest->setUsers($users);

        $result = $this->api->updateStatsWithHttpInfo($brand, $extRef, $statsUpdateRequest);

        $this->assertIsArray($result);
        $this->assertCount(3, $result);
        $this->assertNull($result[0]);
        $this->assertEquals(204, $result[1]);
        $this->assertIsArray($result[2]);
    }

    /**
     * Test case for updateStats with exception
     *
     * Reports the current active user count from the Nextcloud instance to PSS.
     *
     */
    public function testUpdateStatsException()
    {
        $this->mockHandler->append(new Response(400, [], '{"status":"400 BAD_REQUEST","message":"Invalid payload","requestId":"req-1"}'));

        $brand = 'test_brand';
        $extRef = 'test_extRef';

        $users = new \IONOS\NextcloudPSS\AddonsAPI\Client\Model\UserStats();
        $users->setExistingUsers(0);

        $statsUpdateRequest = new \IONOS\NextcloudPSS\AddonsAPI\Client\Model\StatsUpdateRequest();
        $statsUpdateRequest->setTimestamp(new \DateTime('2026-04-29T08:04:05Z'));
        $statsUpdateRequest->setUsers($users);

        $this->expectException(ApiException::class);
        $this->api->updateStats($brand, $extRef, $statsUpdateRequest);
    }

    public function testUpdateStatsAsyncConnectException()
    {
        $brand = 'test_brand';
        $extRef = 'test_extRef';

        $this->mockHandler->append(new ConnectException(
            'Connection refused',
            new Request('PUT', 'https://API_HOST/nextcloud/addons/' . $brand . '/' . $extRef . '/stats')
        ));

        $users = new \IONOS\NextcloudPSS\AddonsAPI\Client\Model\UserStats();
        $users->setExistingUsers(1);

        $statsUpdateRequest = new \IONOS\NextcloudPSS\AddonsAPI\Client\Model\StatsUpdateRequest();
        $statsUpdateRequest->setTimestamp(new \DateTime('2026-04-29T08:04:05Z'));
        $statsUpdateRequest->setUsers($users);

        $this->expectException(ApiException::class);
        $this->api->updateStatsAsync($brand, $extRef, $statsUpdateRequest)->wait();
    }
}
